insert into ads (id, description, title) values (1, 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', 'uniform');
insert into ads (id, description, title) values (2, 'nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 'Vision-oriented');
insert into ads (id, description, title) values (3, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 'User-centric');
insert into ads (id, description, title) values (4, 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 'Enhanced');
insert into ads (id, description, title) values (5, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 'multimedia');
insert into ads (id, description, title) values (6, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', 'Configurable');
insert into ads (id, description, title) values (7, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', 'Enterprise-wide');
insert into ads (id, description, title) values (8, 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 'systematic');
insert into ads (id, description, title) values (9, 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 'uniform');
insert into ads (id, description, title) values (10, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', 'Stand-alone');
insert into ads (id, description, title) values (11, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 'Open-architected');
insert into ads (id, description, title) values (12, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna', 'dynamic');
insert into ads (id, description, title) values (13, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', 'core');
insert into ads (id, description, title) values (14, 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus', 'standardization');
insert into ads (id, description, title) values (15, 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', 'firmware');
insert into ads (id, description, title) values (16, 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', 'capacity');
insert into ads (id, description, title) values (17, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'capacity');
insert into ads (id, description, title) values (18, 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', 'customer loyalty');
insert into ads (id, description, title) values (19, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur', 'executive');
insert into ads (id, description, title) values (20, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', 'full-range');
insert into ads (id, description, title) values (21, 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis', 'focus group');
insert into ads (id, description, title) values (22, 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 'Innovative');
insert into ads (id, description, title) values (23, 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 'analyzer');
insert into ads (id, description, title) values (24, 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla', 'synergy');
insert into ads (id, description, title) values (25, 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus', 'Inverse');
insert into ads (id, description, title) values (26, 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 'foreground');
insert into ads (id, description, title) values (27, 'id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem', 'array');
insert into ads (id, description, title) values (28, 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet', 'Focused');
insert into ads (id, description, title) values (29, 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 'non-volatile');
insert into ads (id, description, title) values (30, 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 'process improvement');
insert into ads (id, description, title) values (31, 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 'stable');
insert into ads (id, description, title) values (32, 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum', 'well-modulated');
insert into ads (id, description, title) values (33, 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 'solution-oriented');
insert into ads (id, description, title) values (34, 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', 'contingency');
insert into ads (id, description, title) values (35, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', 'initiative');
insert into ads (id, description, title) values (36, 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel', 'Object-based');
insert into ads (id, description, title) values (37, 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in', 'capability');
insert into ads (id, description, title) values (38, 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue', 'analyzing');
insert into ads (id, description, title) values (39, 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor', 'support');
insert into ads (id, description, title) values (40, 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie', 'multi-state');
insert into ads (id, description, title) values (41, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio', 'mission-critical');
insert into ads (id, description, title) values (42, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', 'leverage');
insert into ads (id, description, title) values (43, 'luctus ultricies eu nibh quisque id justo sit amet sapien', 'Front-line');
insert into ads (id, description, title) values (44, 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer', 'stable');
insert into ads (id, description, title) values (45, 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse', 'eco-centric');
insert into ads (id, description, title) values (46, 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum', 'optimal');
insert into ads (id, description, title) values (47, 'quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 'Switchable');
insert into ads (id, description, title) values (48, 'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 'parallelism');
insert into ads (id, description, title) values (49, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel', 'Fundamental');
insert into ads (id, description, title) values (50, 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', 'intranet');