use adlister_db;

insert into ads (description, title) values ('morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum', 'matrices');
insert into ads (description, title) values ('at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 'Synchronised');
insert into ads (description, title) values ('ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', 'pricing structure');
insert into ads (description, title) values ('aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', 'Visionary');
insert into ads (description, title) values ('volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam', 'Secured');
insert into ads (description, title) values ('nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et', 'intranet');
insert into ads (description, title) values ('vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 'neural-net');
insert into ads (description, title) values ('et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', 'Customizable');
insert into ads (description, title) values ('blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis', 'neural-net');
insert into ads (description, title) values ('id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 'dedicated');
insert into ads (description, title) values ('molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac', 'impactful');
insert into ads (description, title) values ('accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', 'high-level');
insert into ads (description, title) values ('tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', '5th generation');
insert into ads (description, title) values ('interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 'Graphic Interface');
insert into ads (description, title) values ('amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 'Synchronised');
insert into ads (description, title) values ('tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', 'flexibility');
insert into ads (description, title) values ('in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', 'Compatible');
insert into ads (description, title) values ('tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 'Secured');
insert into ads (description, title) values ('ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', 'solution-oriented');
insert into ads (description, title) values ('nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', 'application');
insert into ads (description, title) values ('leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 'capability');
insert into ads (description, title) values ('morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', 'fresh-thinking');
insert into ads (description, title) values ('proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus', 'Open-source');
insert into ads (description, title) values ('vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 'attitude');
insert into ads (description, title) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 'Integrated');
insert into ads (description, title) values ('ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 'next generation');
insert into ads (description, title) values ('scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', 'foreground');
insert into ads (description, title) values ('eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', 'Triple-buffered');
insert into ads (description, title) values ('sem duis aliquam convallis nunc proin at turpis a pede', 'actuating');
insert into ads (description, title) values ('blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget', 'Total');
insert into ads (description, title) values ('lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam', 'fresh-thinking');
insert into ads (description, title) values ('non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 'exuding');
insert into ads (description, title) values ('interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 'Expanded');
insert into ads (description, title) values ('hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', 'matrices');
insert into ads (description, title) values ('libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas', 'Multi-lateral');
insert into ads (description, title) values ('luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien', 'web-enabled');
insert into ads (description, title) values ('convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget', 'Expanded');
insert into ads (description, title) values ('penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 'Universal');
insert into ads (description, title) values ('lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 'benchmark');
insert into ads (description, title) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam', 'Proactive');
insert into ads (description, title) values ('diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam', 'heuristic');
insert into ads (description, title) values ('natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 'reciprocal');
insert into ads (description, title) values ('pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', 'instruction set');
insert into ads (description, title) values ('purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 'moratorium');
insert into ads (description, title) values ('felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 'focus group');
insert into ads (description, title) values ('ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', 'Digitized');
insert into ads (description, title) values ('congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 'Operative');
insert into ads (description, title) values ('suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', 'moderator');
insert into ads (description, title) values ('elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 'capability');
insert into ads (description, title) values ('in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 'Seamless');